language: c

git:
  depth: 1

matrix:
  fast_finish: true
  allow_failures:
    - env: allegro5-container
  include:
    - env: allegro4-container
      dist: precise
      sudo: false
      addons:
        apt:
          packages:
            - indent
            - libasound2-dev
            - libesd0-dev
            - libjack-dev
            - libxpm-dev
            - libxxf86vm-dev
            - libxml2-utils
            - splint
            - texinfo
      cache:
        directories:
          - $HOME/install/liballegro
      install: . script/travis-ci/deps.sh
      script: script/travis-ci/linux.sh

    - env: allegro4-trusty
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - indent
            - liballegro4.2-dev
            - libxml2-utils
            - splint
#      install: travis_retry sudo apt-get -yq install liballegro4.2-dev
      script: script/travis-ci/linux.sh

    - dist: precise
      sudo: false
      env: allegro5-container
      addons:
        apt:
          packages:
            - indent
            - libdumb1-dev
            - libenet-dev
            - libflac-dev
            - libopenal-dev
            - libphysfs-dev
            - libpulse-dev
            - libtheora-dev
            - libvorbis-dev
            - libxxf86vm-dev
            - p7zip
            - splint
      script: script/travis-ci/linux-allegro5.sh

    #~ - os: osx
      #~ osx_image: xcode8
      #~ install:
        #~ - brew update
        #~ - brew install
            #~ allegro
            #~ scons
#~ #            p7zip freetype libogg physfs libpng flac ffmpeg
      #~ script: script/travis-ci/osx.sh

branches:
  only:
    - master

